### ISSUE TITLE
FYI: Codebase and documentation not in compliance with MITRE ATT&CK® legal trademark requirements

### ISSUE THREAD

**Issue by joachimmetz** [SigmaHQ/sigma#1028]
Have a look at the legal section on "How should I reference the name ATT&CK?"
https://attack.mitre.org/resources/faq/

```
Both MITRE ATT&CK® and ATT&CK® are registered trademarks of The MITRE Corporation.

* Your first references in writing must include "MITRE" preceding "ATT&CK®" - but subsequently should just reference "ATT&CK" (no registered trademark symbol required).
  * Example of a first reference: MITRE ATT&CK® is a curated knowledge base and model for cyber adversary behavior...
  * Example of subsequent reference: ATT&CK is useful for understanding security risk against known adversary behavior...
* A headline should always reference "MITRE ATT&CK" together (never only "ATT&CK®").
* Always capitalize "ATT&CK" to distinguish it from the surrounding text.
* Do not modify the trademark, such as through hyphenation or abbreviation. For example, "ATT&CK'd!", "Plan-of-ATT&CK", "ATTK".
* You may not display the ATT&CK trademark in any manner that implies an affiliation with, sponsorship, or endorsement by MITRE, or in a manner that can be reasonably interpreted to suggest third party content represents the views and opinions of MITRE or MITRE personnel, unless those third parties receive express permission from MITRE.
* You may not use ATT&CK in your product names, service names, trademarks, logos, or company names.
```

**Comment by joachimmetz** [comment]
Please nag attack@mitre.org if you think these requirements are silly (I'm just the messenger)

**Comment by Neo23x0** [comment]
Fixed in commit https://github.com/Neo23x0/sigma/commit/d3ee1aba6654411c94b14f2b2f7d88a41208c5f7

I've removed some references in rules since I don't want to use Non-ASCII characters in rules and added the registered trademark symbol in other places.

**Comment by joachimmetz** [comment]
Thx much appreciated

**Comment by joachimmetz** [comment]
Looks like this is still an issue (or maybe again) https://github.com/SigmaHQ/sigma/blob/08ca62cc8860f4660e945805d0dd615ce75258c1/rules/windows/network_connection/silenttrinity_stager_msbuild_activity.yml

**Comment by Neo23x0** [comment]
I fixed the issue and wrote a trademark test so that new rules get immediately tested for trademark violations
https://github.com/SigmaHQ/sigma/blob/master/tests/test_rules.py#L63

**Comment by joachimmetz** [comment]
thx that will make sure there are no issues there for packaging sigma

**Comment by adampennin** [comment]
@joachimmetz That's certainly not the intent of our guidance. https://github.com/SigmaHQ/sigma/blob/master/README.md is more than sufficient for the project (at the moment 6x more than sufficient since we're only asking for "first reference").

**Comment by joachimmetz** [comment]
@adampennin not sure if I understand your comment. My comment is that you take care of license and other type of legal issues in the original source you don't burden distro packagers with it.

**Comment by joachimmetz** [comment]
@adampennin I see you are likely referring to the legal language of https://attack.mitre.org/resources/faq/ . I've asked Mitre legal to clarify and adjust it, but they were not interested. At the moment "first reference" is unclear for a project that consist of multiple files, technically every file could be considered as an individual piece of work, and thus the "first reference" rule applies to all files.

**Comment by adampennin** [comment]
I'm the person who replied to you from attack@mitre.org. The part of https://attack.mitre.org/resources/faq/ you're having a problem with comes from trademark law and isn't ATT&CK specific. As far as we're concerned Sigma's taken care of any "type of legal issues" with the reference in the README, similar to how you don't have the license in every rule.

**Comment by joachimmetz** [comment]
@adampennin can you put this piece of information in your FAQ that would be very helpful.

**Comment by nasbench** [comment]
This issue was resolved via the addition of the following [test](https://github.com/SigmaHQ/sigma/blob/14cb2f32eb714f08006a07d325409fc872e2a564/tests/test_rules.py#L67-L78) in the `test_rules.py` file.
